Messaging App/Models/AccountSettings.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MessagingApp.Models
{
    public class AccountSettings : DBObject
    {
        public string userName { get; set; }

        public string Email { get; set; }
    }
}

Messaging App/Models/ChangePassword.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MessagingApp.Models
{
    public class ChangePassword
    {
        public string NewPassword { get; set; }
        public string ConfirmPassword { get; set; }
    }
}

Messaging App/Models/Preferences.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MessagingApp.Models
{
    public class Preferences : DBObject
    {
        public string TxtColor { get; set; }

        public string Baccolor { get; set; }

        public string TxtSize { get; set; }

    }
}

Messaging App/Controllers/ChatController.cs
using MessagingApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MySql.Data.MySqlClient;
using Microsoft.AspNetCore.SignalR;
using System.IO;
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;


namespace MessagingApp.Controllers
{
    public class ChatController : Controller
    {
        /*private readonly DBManager _manager;

        public ChatController(DBManager manager)
        {
            _manager = manager;
        }*/
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult TopicSearch(TopicSearchModel topicSearchMod, bool? bResetList)
        {
            if (bResetList == null)
            {
                string privateOption = "public";

                const string connection2 = "server=unitedmessaging.cylirx7dw3jb.us-east-1.rds.amazonaws.com;user id=Unitedmessaging; password = unitedmessaging21; persistsecurityinfo=True;database= united_messaging";
                const string connection3 = "server=unitedmessaging.cylirx7dw3jb.us-east-1.rds.amazonaws.com;user id=Unitedmessaging; password = unitedmessaging21; persistsecurityinfo=True;database= united_messaging";

                MySqlConnection conn2 = new MySqlConnection(connection2);
                MySqlConnection conn3 = new MySqlConnection(connection3);
                MySqlCommand topicSearch = conn2.CreateCommand();
                MySqlCommand topicCategory = conn3.CreateCommand();

                topicCategory.CommandText = "SELECT category FROM topics where privacyOption = @privacyOption"; //command for category
                topicCategory.Parameters.AddWithValue("privacyOption", privateOption);
                conn3.Open();

                MySqlDataReader mRead = topicCategory.ExecuteReader();
                List<string> CategorySearch = new List<string>();

                int i = 0;
                bool categoryExist = false;
                while (mRead.Read())
                {
                    if (i != 0)
                    {
                        for (int counter = 0; counter < CategorySearch.Count(); counter++)
                        {
                            if (Convert.ToString(mRead[0]) == CategorySearch[counter])
                            {
                                categoryExist = true;
                            }
                        }
                        if (categoryExist == false)
                        {
                            CategorySearch.Add(Convert.ToString(mRead[0]));
                            i++;
                        }
                    }
                    else
                    {
                        CategorySearch.Add(Convert.ToString(mRead[0]));
                        i++;
                    }
                    categoryExist = false;
                }
                mRead.Close();
                topicSearchMod.SetCategoryListAttr(CategorySearch);
               conn3.Close();

            }
            // conn3.Close();

            /*  topicSearch.CommandText = "SELECT topicName FROM topics where privacyOption = @privacyOption";
              topicSearch.Parameters.AddWithValue("@privacyOption", privateOption);

              conn2.Open();
              MySqlDataReader lRead = topicSearch.ExecuteReader();
              List<string> TopicSearch = new List<string>();

              while (lRead.Read())
              {
                  TopicSearch.Add(Convert.ToString(lRead[0]));
              }
              lRead.Close();
              conn2.Close();*/

            //topicSearchMod.SetCategoryListAttr(CategorySearch);
            // topicSearchMod.SetTopicsListAttr(TopicSearch);
            return View("TopicSearch");
        }

        public IActionResult GetTopicList(TopicSearchModel TopSerMod, string category)
        {
            /**
             
             WAS TRYING SOMETHING OUT HERE
             */
            string privateOption = "public";

            const string connection7 = "server=unitedmessaging.cylirx7dw3jb.us-east-1.rds.amazonaws.com;user id=Unitedmessaging; password = unitedmessaging21; persistsecurityinfo=True;database= united_messaging";
            MySqlConnection conn7 = new MySqlConnection(connection7);
            MySqlCommand topicSearch = conn7.CreateCommand();

            if(category == "")
            {
                topicSearch.CommandText = "SELECT topicName FROM topics where privacyOption = @privacyOption";
                topicSearch.Parameters.AddWithValue("@privacyOption", privateOption);
            } 
            else
            {
                topicSearch.CommandText = "SELECT topicName FROM topics where privacyOption = @privacyOption AND category = @category";
                topicSearch.Parameters.AddWithValue("@privacyOption", privateOption);
                topicSearch.Parameters.AddWithValue("@category", category);
            }

            conn7.Open();
            MySqlDataReader lRead = topicSearch.ExecuteReader();
            List<string> TopicSearch = new List<string>();

            while (lRead.Read())
            {
                TopicSearch.Add(Convert.ToString(lRead[0]));
            }
            lRead.Close();
            conn7.Close();

            TopSerMod.SetTopicsListAttr(TopicSearch);
            return View("GetTopicList");
        }
        public IActionResult ViewTopic(TopicSearchModel tSM)
        {
            const string connection4 = "server=unitedmessaging.cylirx7dw3jb.us-east-1.rds.amazonaws.com;user id=Unitedmessaging; password = unitedmessaging21; persistsecurityinfo=True;database= united_messaging";
            MySqlConnection conn4 = new MySqlConnection(connection4);
            MySqlCommand viewTopic = conn4.CreateCommand();
            tSM.m_topic = tSM.topicDropdown;
            tSM.m_category = tSM.categoryDropdown;

            viewTopic.CommandText = "SELECT description, topicQuestion FROM topics where category= @category AND topicName= @topicName"; // the command
            viewTopic.Parameters.AddWithValue("@category", tSM.m_category);
            viewTopic.Parameters.AddWithValue("@topicName", tSM.m_topic);
            conn4.Open();
            MySqlDataReader vRead = viewTopic.ExecuteReader();

            while (vRead.Read())
            {
                tSM.m_description = vRead[0].ToString();
                tSM.m_question = vRead[1].ToString();
            }

            vRead.Close();
            conn4.Close();

            DBManager _manager = new DBManager();
            List<Messages> messages = new List<Messages>();
            List<string> users = new List<string>();

            messages = _manager.GetMessagesTopic(tSM.m_topic);
            ViewData["messageobjects"] = messages;

            users = _manager.GettopicUsers(tSM.m_topic);
            ViewData["users"] = users;
            tSM.topicDropdown = tSM.m_topic;

            return View("ViewTopic");
        }

        public IActionResult GetMembers(TopicSearchModel tSM2, string topicN)
        {
            /**
             Not being used 
             **/
            DBManager _manager = new DBManager();
            List<Messages> messages = new List<Messages>();
            List<string> users = new List<string>();

            messages = _manager.GetMessagesTopic(topicN);
            ViewData["messageobjects"] = messages;

            users = _manager.GettopicUsers(topicN);
            ViewData["users"] = users;
            tSM2.topicDropdown = topicN;

            return View();
        }

        public IActionResult JoinTopic(TopicSearchModel topicSearchM)
        {
            const string connection6 = "server=unitedmessaging.cylirx7dw3jb.us-east-1.rds.amazonaws.com;user id=Unitedmessaging; password = unitedmessaging21; persistsecurityinfo=True;database= united_messaging";
            MySqlConnection conn6 = new MySqlConnection(connection6);

            //string txtCmd = $"SELECT (privacyOption, username, contactName) FROM topics WHERE topicName= @topicName2";
            MySqlCommand joinTopic = conn6.CreateCommand();
            joinTopic.CommandText = $"SELECT privacyOption, contactName FROM topics WHERE topicName= @topicName2";
            joinTopic.Parameters.AddWithValue("@topicName2", topicSearchM.m_topic);
            conn6.Open();
            MySqlDataReader jRead = joinTopic.ExecuteReader();

            while (jRead.Read())
            {
                topicSearchM.radioField = jRead[0].ToString();
                topicSearchM.m_contactName = jRead[1].ToString();
            }
            jRead.Close();

            int userIdTopic = 0;
            string txtCmd3 = $"SELECT id FROM users where username='" + topicSearchM.m_contactName + "'"; // the command
            MySqlCommand cmd3 = new MySqlCommand(txtCmd3, conn6);
            MySqlDataReader hRead;
            using (hRead = cmd3.ExecuteReader()) // executes the search command
            {
                if (hRead.Read())
                {
                    userIdTopic = Convert.ToInt32(hRead[0]);
                }
            }
            hRead.Close();


            string txtCmd4 = $"SELECT userName FROM topics where userId='" + DBObject.m_id + "' and topicName = '" + topicSearchM.m_topic + "'"; // the command
            MySqlCommand cmd4 = new MySqlCommand(txtCmd4, conn6);
            MySqlDataReader mRead;
            using (mRead = cmd4.ExecuteReader()) // executes the search command
            {
                if (mRead.Read())
                {
                }

                else
                {
                    mRead.Close();
                    //for adding user on one end

Messaging App/Views/Home/AccountSettings.cshtml
@model MessagingApp.Models.AccountSettings
@{
    Layout = null;
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/AccountSettingsStyleSheet.css" />
    ViewBag.message = TempData["Password Changed"];
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<!--<body class="AccountSettings">-->
<body>
    <form asp-action="AccountSettings" method="post">
        <div class=" surr">
            <div class=" k">


                <!--   <div class=" test">-->
                <h1>Account Settings</h1>
                <!-- </div>-->
                <!-- <div class=" out">-->
                <!--<div asp-validation-summary="ModelOnly" class="text-danger"></div>-->
                <!-- <div class=" d">-->
                <p9>UserName:</p9>
                <!--</div>-->


                <input type="text" disabled="disabled" class="trigger" id="userNameInput" asp-for="userName" />
                <br>
                <span asp-validation-for="userName" class="text-danger"></span>

                <br />

                <br />

                <!--<div class=" r">-->
                <p10>Email:</p10>
                <!-- </div>-->




                <input type="text" class="trigger" id="EmailInput" asp-for="Email" />
                <br>
                <span asp-validation-for="Email" class="text-danger"></span>
                <br />

                <br />
                <br />
                <!--
                         <p4>Profile Picture:</p4>
              <br />
              <br />
              <br />



              <div id="profile-container">
                  <image id="profileImage" src="" />
                  <input id="imageUpload" class="fileUpload" type="file" name="profile_photo" placeholder="Photo" require="" capture onclick="location.href='@Url.Action("savePicture", "Home")'" />
              </div>

            -->

               <!-- <div class="second">-->
                    <button class="button button1" id="ApplyButton" type="submit" onclick="location.href='@Url.Action(" AccountSettings", "Home" )'"> Apply Changes</button>
                    <!--  <button class="button button2">Cancel</button>-->
                    <button class="button button3" type="button" onclick="location.href='@Url.Action("ChangePasswordScreen", "Home" )'">Change Password</button>
               <!-- </div>-->
            </div>

        </div>


        <!--</div>-->
        </form>
    </body>
    </html>
    @if (ViewBag.Message != null)
    {
        <script type="text/javascript">
        window.onload = function () {
            alert("@ViewBag.Message");
        };
        </script>
    }

Messaging App/Views/Home/ChangePassword.cshtml
@model MessagingApp.Models.LoginChangePasswordModel
@{
    Layout = null;
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/ChangePasswordStyleSheet.css" />
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body class="ChangePasswordBackground">
    <form asp-action="ChangePassword" method="post">
        <div class="ChangePasswordForm">
            <h3>Change Password</h3>
            <div class="fields">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <p>
                    <label id="NewPasswordLabel" asp-for="NewPassword"></label>
                    <input type="text" class="trigger" id="NewPasswordInput" asp-for="NewPassword" />
                    <br>
                    <span asp-validation-for="NewPassword" class="text-danger"></span>
                </p>
                <p>
                    <label id="ConfirmPasswordLabel" asp-for="ConfirmPassword"></label>
                    <input type="text" class="trigger" id="NewPasswordInput" asp-for="ConfirmPassword" />
                    <br>
                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                </p>
            </div>
            <button id="ResetPasswordButton" type="submit" onclick="location.href='@Url.Action("ChangePassword", "Home")'">Reset Password</button>
            <button id="CancelButton" type="button" onclick="location.href='@Url.Action("AccountSettings", "Home")'">Cancel</button>
        </div>
    </form>
</body>
</html>

@if (ViewBag.Message != null)
{
<script type="text/javascript">
    window.onload = function () {
        alert("@ViewBag.Message");
    };
</script>
}

Messaging App/Views/Home/Contacts.cshtml
@model MessagingApp.Models.ContactsModel

@{
    // Use login layout under View->Shared folder
    Layout = "_Layout";
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/ContactsStyleSheet.css" />
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <div class="contactContainer">
        <form>
            <fieldset class="centered contactSearchArea" asp-action="ContactsTemplate">
                <h1 style="text-align:center; margin-top: 5px;">Contacts</h1>
                <div class="fields">
                    <p>
                        <label class="addContactLabel">Add contact:</label>
                        <input type="text" id="addContactInput" asp-for="addContactInput" />
                        <br>
                        <!--<div class="centered buttonArea">-->
                        <button class="addContactButton" type="submit" onclick="location.href='@Url.Action("Contacts", "Home")'">Add Contact</button>
                        <!--</div>-->
                        <br />
                    </p>
                </div>
            </fieldset>
        </form>
        <form class="centered viewContactsArea" asp-action="GroupTemplate" method="post">
            <div class="fields">
                <label class="contactLabel">Your Contact Requests From Others:</label>
                <br>
                <dl>
                    @for (int k = 0; k < HomeModel.m_contactslist.Count; k++)
                    {
                        @if (HomeModel.m_contactnumber[k] == 0 && HomeModel.m_contactSender[k] == 0)
                        {
                            <h3>@HomeModel.m_contactslist[k]</h3>
                            <button style="display: inline-block; width: 36px; height: 36px; margin-top: 0px; color: white; background-color:dodgerblue; font-size: 16px;" type="button" dis onclick="location.href='@Url.Action("EditContacts", "Home", new { username = HomeModel.m_contactslist[k] })'">✔ </button>
                            <button style="display: inline-block; width: 36px; height: 36px; margin-top: 0px; color: white; background-color:dodgerblue; font-size: 16px;" type="button" dis onclick="location.href='@Url.Action("removeContact", "Home", new { contact = @HomeModel.m_contactslist[k] })'">✘ </button>
                            <br>
                            <br>
                        }
                    }
                </dl>
                <br>

                <label class="contactLabel">Your Pending Requests From You:</label>
                <br>
                <dl>
                    @for (int k = 0; k < HomeModel.m_contactslist.Count; k++)
                    {
                        @if (HomeModel.m_contactnumber[k] == 0 && HomeModel.m_contactSender[k] == 1)
                        {
                            <h3>@HomeModel.m_contactslist[k]</h3>
                            <button style="display: inline-block; width: 36px; height: 36px; margin-top: 0px; color: white; background-color:dodgerblue; font-size: 16px;" type="button" dis onclick="location.href='@Url.Action("removeContact", "Home", new { contact = @HomeModel.m_contactslist[k] })'">✘ </button>
                            <br>
                            <br>
                        }
                    }
                </dl>
                <br>

                <label class="contactLabel">Your Contacts:</label>
                <br>

                <dl>

                    @for (int i = 0; i < HomeModel.m_contactslist.Count; i++)
                    {
                        @if (HomeModel.m_contactnumber[i] == 1)
                        {
                            <h3>@HomeModel.m_contactslist[i]</h3>
                            <!-- <button style="display: inline-block; width: 36px; height: 36px; margin-top: 0px; color: white; background-color:dodgerblue; font-size: 16px;" type="button" dis onclick="location.href='@Url.Action("removeContact", "Home", new {contact = @HomeModel.m_contactslist[i]})'">🗑️ </button>-->
                            <button style="display: inline-block; width: 36px; height: 36px; margin-top: 0px; background: url(../../Images/trashCan.jpg); background-size: cover;" type="button" dis onclick="location.href='@Url.Action("removeContact", "Home", new {contact = @HomeModel.m_contactslist[i]})'"></button>
                            <br>
                            <br>
                        }
                    }
                </dl>
                <br>
                <br>
            </div>
        </form>
        <div class="homeButton">
            <button class="goHomeButton" type="button" onclick="location.href='@Url.Action("Home", "Home")'">Home</button>
        </div>
    </div>
</body>
</html>
@if (ViewBag.Message != null)
{
<script type="text/javascript">
    window.onload = function () {
        alert("@ViewBag.Message");
    };
</script>
}

Messaging App/Views/Home/Home.cshtml
@model MessagingApp.Models.HomeModel
@{
    // Use login layout under View->Shared folder
    Layout = "_Layout";
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/HomePageStyleSheet.css" />
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <div class="LeftSideButton">
        <img id="LoginLogo" src="/Images/Logo.png" />

        <button id="ProfileButton" type="submit" onclick="location.href='@Url.Action("Profile", "Home")'">Profile</button>
        <button id="TopicSearchButton" type="submit" onclick="location.href='@Url.Action("TopicSearch", "Chat")'">Search For Topics</button>
        <button id="CreateGroupButton" type="button" onclick="location.href='@Url.Action("CreateGroupScreen", "Chat")'">Create Group</button>
        <button id="ContactsButton" type="submit" onclick="location.href='@Url.Action("Contacts", "Home")'">Contacts</button>

        <h2>Joined Groups</h2>
        <div id="ScrollBoxGroup">
            @{
                for (int i = 0; i < HomeModel.m_grouplist.Count; i++)
                {
                    <button id="groupButtons" name="button" type="submit" value="@HomeModel.m_grouplist[i]" onclick="location.href='@Url.Action("GroupTemplate", "Chat")?name=@HomeModel.m_grouplist[i]'">@HomeModel.m_grouplist[i]</button>;
                }
            }
        </div>
        <h2>Joined Topics</h2>
        <div id="ScrollBoxTopic">
            @{
                for (int j = 0; j < HomeModel.m_topiclist.Count; j++)
                {
                    <button id="topicButtons" name="button" type="submit" value="@HomeModel.m_topiclist[j]" onclick="location.href='@Url.Action("TopicTemplate", "Chat")?name=@HomeModel.m_topiclist[j]'">@HomeModel.m_topiclist[j] </button>;
                }
            }
        </div>
    </div>
    <div class="RightSide">
        <button class="centered" id="LoginScreenButton" type="submit" onclick="location.href='@Url.Action("Index", "Login")'">Log Out</button>

        <div class="contactArea">
            <h1>Contacts</h1>
            @{
                for (int i = 0; i < HomeModel.m_contactsListHomeScreen.Count(); i++)
                {
                    <p>
                        <h3>@HomeModel.m_contactsListHomeScreen[i] </h3>
                    </p>
                }
            }


        </div>
        <div class="topGroupArea">
            <h1>Top 3 Groups</h1>

            @{
                Dictionary<string, int> groupDictionary = new Dictionary<string, int>();
                groupDictionary = ViewData["groupCount"] as Dictionary<string, int>;
                int counterGroups = 1;
                <p>
                    @foreach (KeyValuePair<string, int>
                 group in groupDictionary)
                    {
                        <h3 style="margin-top: 12%">@counterGroups.  @group.Key with @group.Value messages</h3>
                        <br>
                        counterGroups = counterGroups + 1;

                    }
                </p>

                <p>
                    <h1> Group Requests</h1>
                    <dl>
                        @for (int k = 0; k < HomeModel.m_groupinvitelist.Count; k++)
                        {
                            @if (HomeModel.m_Invite[k] == 1 && HomeModel.m_InviteGroupContact[k] != DBObject.m_username && HomeModel.m_groupuserName[k] == DBObject.m_username )
                            {
                        <h3>
                            @HomeModel.m_groupinvitelist[k]
                                                        <button style="display: inline-block; width: 36px; height: 36px; margin-top: 0px; color: white; background-color:dodgerblue; font-size: 16px;" type="button" dis onclick="location.href='@Url.Action("EditgroupInvite", "Home", new { chatName = @HomeModel.m_groupinvitelist[k] })'">✔ </button>
                                                        <button style="display: inline-block; width: 36px; height: 36px; margin-top: 0px; color: white; background-color:dodgerblue; font-size: 16px;" type="button" dis onclick="location.href='@Url.Action("removeGroupInvite", "Home", new { chatName = @HomeModel.m_groupinvitelist[k] })'">✘ </button>
                                                    </h3>
                            }
                        }
                    </dl>
                    <br>

                </p>

                <p>
                    <h1> Pending Group Requests</h1>
                    <dl>
                        @for (int k = 0; k < HomeModel.m_groupinvitelist.Count; k++)
                        {
                            @if (HomeModel.m_Invite[k] == 1  && HomeModel.m_InviteGroupContact[k] == DBObject.m_username)
                            {
                        <h3>
                            @HomeModel.m_groupuserName[k] has not joined the group: @HomeModel.m_groupinvitelist[k]
                           <button style="display: inline-block; width: 36px; height: 36px; margin-top: 0px; color: white; background-color:dodgerblue; font-size: 16px;" type="button" dis onclick="location.href='@Url.Action("removeGroupInvite", "Home", new { chatName = @HomeModel.m_groupinvitelist[k],userName = HomeModel.m_groupuserName[k] })'">✘ </button>
                         </h3>
                             }
                        }
                    </dl>
                    <br>

                </p>
            }

        </div>

        <div class="topTopicArea">
            <h1>Top 3 Topics</h1>
            @{
                Dictionary<string, int> topicDictionary = new Dictionary<string, int>();
                List<string> categoryList = new List<string>();
                topicDictionary = ViewData["topicCount"] as Dictionary<string, int>;
                categoryList = ViewData["topicCategory"] as List<string>;
                int counter = 1;
                <p>
                    @foreach (KeyValuePair<string, int>
                 topic in topicDictionary)
                    {
                        <h3 style="margin-top: 12%">
                            @counter.  @topic.Key in the category @categoryList[counter - 1]
                            with @topic.Value messages
                        </h3>
                        <br>
                        counter = counter + 1;

                    }
                </p>

                <p>
                    <h1> Topic Requests</h1>
                    <dl>
                        @for (int k = 0; k < HomeModel.m_topicinvitelist.Count; k++)
                        {
                            @if (HomeModel.m_Invitetopic[k] == 1 && HomeModel.m_InvitetopicContact[k] != DBObject.m_username && HomeModel.m_topicuserName[k] == DBObject.m_username)
                            {
                                <h3>
                                    @HomeModel.m_topicinvitelist[k]
                                    <button style="display: inline-block; width: 36px; height: 36px; margin-top: 0px; color: white; background-color:dodgerblue; font-size: 16px;" type="button" dis onclick="location.href='@Url.Action("EdittopicInvite", "Home", new { chatName = @HomeModel.m_topicinvitelist[k] })'">✔ </button>
                                    <button style="display: inline-block; width: 36px; height: 36px; margin-top: 0px; color: white; background-color:dodgerblue; font-size: 16px;" type="button" dis onclick="location.href='@Url.Action("removetopicInvite", "Home", new { chatName = @HomeModel.m_topicinvitelist[k] })'">✘ </button>
                                </h3>
                            }
                        }
                    </dl>
                    <br>

                </p>

                <p>
                    <h1> Pending Topic Requests</h1>
                    <dl>
                        @for (int k = 0; k < HomeModel.m_topicinvitelist.Count; k++)
                        {
                            @if (HomeModel.m_Invitetopic[k] == 1 && HomeModel.m_InvitetopicContact[k] == DBObject.m_username)
                            {
                        <h3>
                            @HomeModel.m_topicuserName[k] has not joined the group: @HomeModel.m_topicinvitelist[k]
                            <button style="display: inline-block; width: 36px; height: 36px; margin-top: 0px; color: white; background-color:dodgerblue; font-size: 16px;" type="button" dis onclick="location.href='@Url.Action("removetopicInvite", "Home", new { chatName = @HomeModel.m_topicinvitelist[k],userName = HomeModel.m_topicuserName[k] })'">✘ </button>
                        </h3>
                            }
                        }
                    </dl>
                    <br>

                </p>
            }

        </div>


    </div>
</body>
</html>